# 模块领域：数据库迁移层
# 领域说明：负责用版本化脚本维护数据库结构变更。
# 文件职责：业务代码文件。承载本模块的一部分领域能力或工程能力。
# 维护原则：本文件只补充业务/工程注释，不在注释中改变任何运行逻辑。

"""add_family_permission_tables

Revision ID: 278ab15ff9ab
Revises: c4d4c2b2ef2e
Create Date: 2026-07-03 12:31:00.152538

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '278ab15ff9ab'
down_revision: str | None = 'c4d4c2b2ef2e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# 函数职责：数据库升级函数，创建或调整当前迁移版本需要的表、字段、索引和约束。
# 业务边界：迁移必须可重复追踪，不能依赖运行时业务状态。
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 流程说明：
    # 1. 按迁移版本声明数据库结构变化。
    # 2. 由 Alembic 在部署或本地开发时统一执行。
    # 3. 迁移脚本只处理结构，不处理业务数据解释。
    op.create_table('families',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_families_owner_user_id', 'families', ['owner_user_id'], unique=False)
    op.create_table('family_invitations',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('inviter_user_id', sa.Uuid(), nullable=False),
    sa.Column('invite_code', sa.String(length=64), nullable=False),
    sa.Column('invitee_phone', sa.String(length=32), nullable=True),
    sa.Column('invitee_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'expired', 'cancelled', name='familyinvitationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code', name='uq_family_invitations_invite_code')
    )
    op.create_index('ix_family_invitations_expires_at', 'family_invitations', ['expires_at'], unique=False)
    op.create_index('ix_family_invitations_family_id', 'family_invitations', ['family_id'], unique=False)
    op.create_index('ix_family_invitations_status', 'family_invitations', ['status'], unique=False)
    op.create_table('family_members',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='familyrole', native_enum=False, length=32), nullable=False),
    sa.Column('relationship_label', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'left', 'removed', name='familymemberstatus', native_enum=False, length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_family_members_family_id_user_id')
    )
    op.create_index('ix_family_members_family_id', 'family_members', ['family_id'], unique=False)
    op.create_index('ix_family_members_status', 'family_members', ['status'], unique=False)
    op.create_index('ix_family_members_user_id', 'family_members', ['user_id'], unique=False)
    op.create_table('member_share_permissions',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('share_all', sa.Boolean(), nullable=False),
    sa.Column('can_view_profile', sa.Boolean(), nullable=False),
    sa.Column('can_view_metrics', sa.Boolean(), nullable=False),
    sa.Column('can_view_reports', sa.Boolean(), nullable=False),
    sa.Column('can_view_symptoms', sa.Boolean(), nullable=False),
    sa.Column('can_view_medical_events', sa.Boolean(), nullable=False),
    sa.Column('can_view_documents', sa.Boolean(), nullable=False),
    sa.Column('can_view_alerts', sa.Boolean(), nullable=False),
    sa.Column('can_view_memory_summary', sa.Boolean(), nullable=False),
    sa.Column('can_create_symptom_records', sa.Boolean(), nullable=False),
    sa.Column('can_create_metric_records', sa.Boolean(), nullable=False),
    sa.Column('can_upload_documents', sa.Boolean(), nullable=False),
    sa.Column('can_create_medical_events', sa.Boolean(), nullable=False),
    sa.Column('can_generate_reports', sa.Boolean(), nullable=False),
    sa.Column('can_generate_doctor_visit_summary', sa.Boolean(), nullable=False),
    sa.Column('can_export_summary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_member_share_permissions_family_id_user_id')
    )
    op.create_index('ix_member_share_permissions_family_id', 'member_share_permissions', ['family_id'], unique=False)
    op.create_index('ix_member_share_permissions_share_all', 'member_share_permissions', ['share_all'], unique=False)
    op.create_index('ix_member_share_permissions_user_id', 'member_share_permissions', ['user_id'], unique=False)
    op.create_table('permission_audit_logs',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('grant', 'revoke', 'update', 'reset', name='permissionauditaction', native_enum=False, length=32), nullable=False),
    sa.Column('permission_type', sa.String(length=100), nullable=True),
    sa.Column('before_snapshot', sa.JSON(), nullable=True),
    sa.Column('after_snapshot', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permission_audit_logs_action', 'permission_audit_logs', ['action'], unique=False)
    op.create_index('ix_permission_audit_logs_actor_user_id', 'permission_audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_permission_audit_logs_created_at', 'permission_audit_logs', ['created_at'], unique=False)
    op.create_index('ix_permission_audit_logs_family_id', 'permission_audit_logs', ['family_id'], unique=False)
    op.create_index('ix_permission_audit_logs_target_user_id', 'permission_audit_logs', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


# 函数职责：数据库回滚函数，撤销当前迁移版本引入的数据库结构变化。
# 业务边界：回滚顺序通常要与升级顺序相反，避免外键依赖失败。
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 流程说明：
    # 1. 按迁移版本声明数据库结构变化。
    # 2. 由 Alembic 在部署或本地开发时统一执行。
    # 3. 迁移脚本只处理结构，不处理业务数据解释。
    op.drop_index('ix_permission_audit_logs_target_user_id', table_name='permission_audit_logs')
    op.drop_index('ix_permission_audit_logs_family_id', table_name='permission_audit_logs')
    op.drop_index('ix_permission_audit_logs_created_at', table_name='permission_audit_logs')
    op.drop_index('ix_permission_audit_logs_actor_user_id', table_name='permission_audit_logs')
    op.drop_index('ix_permission_audit_logs_action', table_name='permission_audit_logs')
    op.drop_table('permission_audit_logs')
    op.drop_index('ix_member_share_permissions_user_id', table_name='member_share_permissions')
    op.drop_index('ix_member_share_permissions_share_all', table_name='member_share_permissions')
    op.drop_index('ix_member_share_permissions_family_id', table_name='member_share_permissions')
    op.drop_table('member_share_permissions')
    op.drop_index('ix_family_members_user_id', table_name='family_members')
    op.drop_index('ix_family_members_status', table_name='family_members')
    op.drop_index('ix_family_members_family_id', table_name='family_members')
    op.drop_table('family_members')
    op.drop_index('ix_family_invitations_status', table_name='family_invitations')
    op.drop_index('ix_family_invitations_family_id', table_name='family_invitations')
    op.drop_index('ix_family_invitations_expires_at', table_name='family_invitations')
    op.drop_table('family_invitations')
    op.drop_index('ix_families_owner_user_id', table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
