# 模块领域：数据库迁移层
# 领域说明：负责用版本化脚本维护数据库结构变更。
# 文件职责：业务代码文件。承载本模块的一部分领域能力或工程能力。
# 维护原则：本文件只补充业务/工程注释，不在注释中改变任何运行逻辑。

"""add_medical_document_report_alert_tables

Revision ID: 97c8ad8504bb
Revises: d6cf10a352c9
Create Date: 2026-07-03 12:47:30.075853

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '97c8ad8504bb'
down_revision: str | None = 'd6cf10a352c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# 函数职责：数据库升级函数，创建或调整当前迁移版本需要的表、字段、索引和约束。
# 业务边界：迁移必须可重复追踪，不能依赖运行时业务状态。
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 流程说明：
    # 1. 按迁移版本声明数据库结构变化。
    # 2. 由 Alembic 在部署或本地开发时统一执行。
    # 3. 迁移脚本只处理结构，不处理业务数据解释。
    op.create_table('alerts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.Enum('metric_attention', 'symptom_follow_up', 'medical_follow_up', 'medication_reminder', 'data_missing', 'document_review', name='alerttype', native_enum=False, length=32), nullable=False),
    sa.Column('level', sa.Enum('info', 'attention', 'important', 'urgent', name='alertlevel', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.String(length=500), nullable=True),
    sa.Column('related_entity_type', sa.String(length=100), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'read', 'resolved', 'dismissed', 'expired', name='alertstatus', native_enum=False, length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('rule', 'agent', 'user', 'system', name='alertsource', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_alert_type', 'alerts', ['alert_type'], unique=False)
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_due_at', 'alerts', ['due_at'], unique=False)
    op.create_index('ix_alerts_family_id', 'alerts', ['family_id'], unique=False)
    op.create_index('ix_alerts_level', 'alerts', ['level'], unique=False)
    op.create_index('ix_alerts_related_entity_type_related_entity_id', 'alerts', ['related_entity_type', 'related_entity_id'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_user_id', 'alerts', ['user_id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('overall_status', sa.String(length=100), nullable=True),
    sa.Column('status_level', sa.Enum('normal', 'attention', 'follow_up', 'insufficient_data', name='dailyreportstatuslevel', native_enum=False, length=32), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('concerns', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=True),
    sa.Column('related_symptom_record_ids', sa.JSON(), nullable=True),
    sa.Column('related_alert_ids', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.Enum('system', 'user', 'agent', name='dailyreportgeneratedby', native_enum=False, length=32), nullable=False),
    sa.Column('generation_status', sa.Enum('pending', 'success', 'failed', 'skipped', name='dailyreportgenerationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'report_date', name='uq_daily_reports_user_id_report_date')
    )
    op.create_index('ix_daily_reports_created_at', 'daily_reports', ['created_at'], unique=False)
    op.create_index('ix_daily_reports_family_id', 'daily_reports', ['family_id'], unique=False)
    op.create_index('ix_daily_reports_generation_status', 'daily_reports', ['generation_status'], unique=False)
    op.create_index('ix_daily_reports_report_date', 'daily_reports', ['report_date'], unique=False)
    op.create_index('ix_daily_reports_status_level', 'daily_reports', ['status_level'], unique=False)
    op.create_index('ix_daily_reports_user_id', 'daily_reports', ['user_id'], unique=False)
    op.create_table('medical_documents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('checkup_report', 'medical_record', 'lab_test', 'surgery_record', 'discharge_summary', 'prescription', 'doctor_advice', 'image_note', 'other', name='documenttype', native_enum=False, length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('document_date_text', sa.String(length=100), nullable=True),
    sa.Column('hospital_or_org', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_extract_status', sa.Enum('not_started', 'processing', 'success', 'failed', 'needs_review', 'confirmed', name='documentextractstatus', native_enum=False, length=32), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('extracted_json', sa.JSON(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_event_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('upload', 'manual', 'imported', 'system', name='documentsource', native_enum=False, length=32), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'family_shared', name='documentvisibility', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medical_documents_ai_extract_status', 'medical_documents', ['ai_extract_status'], unique=False)
    op.create_index('ix_medical_documents_created_at', 'medical_documents', ['created_at'], unique=False)
    op.create_index('ix_medical_documents_document_date', 'medical_documents', ['document_date'], unique=False)
    op.create_index('ix_medical_documents_document_type', 'medical_documents', ['document_type'], unique=False)
    op.create_index('ix_medical_documents_family_id', 'medical_documents', ['family_id'], unique=False)
    op.create_index('ix_medical_documents_uploaded_by_user_id', 'medical_documents', ['uploaded_by_user_id'], unique=False)
    op.create_index('ix_medical_documents_user_id', 'medical_documents', ['user_id'], unique=False)
    op.create_index('ix_medical_documents_visibility', 'medical_documents', ['visibility'], unique=False)
    op.create_table('medical_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('checkup', 'outpatient_visit', 'hospitalization', 'surgery', 'medication', 'allergy', 'chronic_condition', 'lab_test', 'doctor_advice', 'follow_up', 'other', name='medicaleventtype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_date_text', sa.String(length=100), nullable=True),
    sa.Column('hospital_or_org', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('diagnosis_text', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('doctor_advice', sa.Text(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('follow_up_needed', sa.Boolean(), nullable=False),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_document_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'document_extracted', 'imported', 'system', name='medicaleventsource', native_enum=False, length=32), nullable=False),
    sa.Column('confidence_level', sa.Enum('high', 'medium', 'low', 'unknown', name='confidencelevel', native_enum=False, length=32), nullable=False),
    sa.Column('timeline_visible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', 'deleted', name='medicaleventstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medical_events_created_at', 'medical_events', ['created_at'], unique=False)
    op.create_index('ix_medical_events_created_by_user_id', 'medical_events', ['created_by_user_id'], unique=False)
    op.create_index('ix_medical_events_event_date', 'medical_events', ['event_date'], unique=False)
    op.create_index('ix_medical_events_event_type', 'medical_events', ['event_type'], unique=False)
    op.create_index('ix_medical_events_family_id', 'medical_events', ['family_id'], unique=False)
    op.create_index('ix_medical_events_follow_up_at', 'medical_events', ['follow_up_at'], unique=False)
    op.create_index('ix_medical_events_follow_up_needed', 'medical_events', ['follow_up_needed'], unique=False)
    op.create_index('ix_medical_events_related_document_id', 'medical_events', ['related_document_id'], unique=False)
    op.create_index('ix_medical_events_status', 'medical_events', ['status'], unique=False)
    op.create_index('ix_medical_events_user_id', 'medical_events', ['user_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('created', 'read', 'resolved', 'dismissed', 'reopened', 'expired', name='alerteventtype', native_enum=False, length=32), nullable=False),
    sa.Column('before_status', sa.Enum('active', 'read', 'resolved', 'dismissed', 'expired', name='alertstatus', native_enum=False, length=32), nullable=True),
    sa.Column('after_status', sa.Enum('active', 'read', 'resolved', 'dismissed', 'expired', name='alertstatus', native_enum=False, length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_events_actor_user_id', 'alert_events', ['actor_user_id'], unique=False)
    op.create_index('ix_alert_events_alert_id', 'alert_events', ['alert_id'], unique=False)
    op.create_index('ix_alert_events_created_at', 'alert_events', ['created_at'], unique=False)
    op.create_index('ix_alert_events_event_type', 'alert_events', ['event_type'], unique=False)
    op.create_table('document_processing_jobs',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', sa.Enum('text_read', 'ocr', 'ai_extract', 'event_draft_generate', name='documentprocessingjobtype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'success', 'failed', 'cancelled', name='documentprocessingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['medical_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_processing_jobs_created_at', 'document_processing_jobs', ['created_at'], unique=False)
    op.create_index('ix_document_processing_jobs_document_id', 'document_processing_jobs', ['document_id'], unique=False)
    op.create_index('ix_document_processing_jobs_family_id', 'document_processing_jobs', ['family_id'], unique=False)
    op.create_index('ix_document_processing_jobs_job_type', 'document_processing_jobs', ['job_type'], unique=False)
    op.create_index('ix_document_processing_jobs_status', 'document_processing_jobs', ['status'], unique=False)
    op.create_index('ix_document_processing_jobs_user_id', 'document_processing_jobs', ['user_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['medical_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_versions_created_at', 'document_versions', ['created_at'], unique=False)
    op.create_index('ix_document_versions_created_by_user_id', 'document_versions', ['created_by_user_id'], unique=False)
    op.create_index('ix_document_versions_document_id', 'document_versions', ['document_id'], unique=False)
    op.create_index('uq_document_versions_document_id_version_no', 'document_versions', ['document_id', 'version_no'], unique=True)
    op.create_table('document_extraction_results',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('processing_job_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('extraction_mode', sa.Enum('basic', 'standard', 'detailed', name='documentextractionmode', native_enum=False, length=32), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('doctor_advice', sa.Text(), nullable=True),
    sa.Column('suggested_events', sa.JSON(), nullable=True),
    sa.Column('raw_extracted_text', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Enum('high', 'medium', 'low', 'unknown', name='confidencelevel', native_enum=False, length=32), nullable=False),
    sa.Column('safety_notes', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'needs_review', 'confirmed', 'rejected', 'failed', name='documentextractionresultstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['medical_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processing_job_id'], ['document_processing_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_extraction_results_confidence_level', 'document_extraction_results', ['confidence_level'], unique=False)
    op.create_index('ix_document_extraction_results_created_at', 'document_extraction_results', ['created_at'], unique=False)
    op.create_index('ix_document_extraction_results_document_id', 'document_extraction_results', ['document_id'], unique=False)
    op.create_index('ix_document_extraction_results_family_id', 'document_extraction_results', ['family_id'], unique=False)
    op.create_index('ix_document_extraction_results_processing_job_id', 'document_extraction_results', ['processing_job_id'], unique=False)
    op.create_index('ix_document_extraction_results_status', 'document_extraction_results', ['status'], unique=False)
    op.create_index('ix_document_extraction_results_user_id', 'document_extraction_results', ['user_id'], unique=False)
    op.create_table('medical_event_drafts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('extraction_result_id', sa.Uuid(), nullable=True),
    sa.Column('draft_event_type', sa.Enum('checkup', 'outpatient_visit', 'hospitalization', 'surgery', 'medication', 'allergy', 'chronic_condition', 'lab_test', 'doctor_advice', 'follow_up', 'other', name='medicaleventtype', native_enum=False, length=32), nullable=False),
    sa.Column('draft_title', sa.String(length=200), nullable=True),
    sa.Column('draft_json', sa.JSON(), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.Enum('high', 'medium', 'low', 'unknown', name='confidencelevel', native_enum=False, length=32), nullable=False),
    sa.Column('safety_flags', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'expired', name='medicaleventdraftstatus', native_enum=False, length=32), nullable=False),
    sa.Column('confirmed_event_id', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['extraction_result_id'], ['document_extraction_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['medical_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medical_event_drafts_confirmed_event_id', 'medical_event_drafts', ['confirmed_event_id'], unique=False)
    op.create_index('ix_medical_event_drafts_created_at', 'medical_event_drafts', ['created_at'], unique=False)
    op.create_index('ix_medical_event_drafts_created_by_user_id', 'medical_event_drafts', ['created_by_user_id'], unique=False)
    op.create_index('ix_medical_event_drafts_draft_event_type', 'medical_event_drafts', ['draft_event_type'], unique=False)
    op.create_index('ix_medical_event_drafts_extraction_result_id', 'medical_event_drafts', ['extraction_result_id'], unique=False)
    op.create_index('ix_medical_event_drafts_family_id', 'medical_event_drafts', ['family_id'], unique=False)
    op.create_index('ix_medical_event_drafts_source_document_id', 'medical_event_drafts', ['source_document_id'], unique=False)
    op.create_index('ix_medical_event_drafts_status', 'medical_event_drafts', ['status'], unique=False)
    op.create_index('ix_medical_event_drafts_user_id', 'medical_event_drafts', ['user_id'], unique=False)
    # ### end Alembic commands ###


# 函数职责：数据库回滚函数，撤销当前迁移版本引入的数据库结构变化。
# 业务边界：回滚顺序通常要与升级顺序相反，避免外键依赖失败。
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 流程说明：
    # 1. 按迁移版本声明数据库结构变化。
    # 2. 由 Alembic 在部署或本地开发时统一执行。
    # 3. 迁移脚本只处理结构，不处理业务数据解释。
    op.drop_index('ix_medical_event_drafts_user_id', table_name='medical_event_drafts')
    op.drop_index('ix_medical_event_drafts_status', table_name='medical_event_drafts')
    op.drop_index('ix_medical_event_drafts_source_document_id', table_name='medical_event_drafts')
    op.drop_index('ix_medical_event_drafts_family_id', table_name='medical_event_drafts')
    op.drop_index('ix_medical_event_drafts_extraction_result_id', table_name='medical_event_drafts')
    op.drop_index('ix_medical_event_drafts_draft_event_type', table_name='medical_event_drafts')
    op.drop_index('ix_medical_event_drafts_created_by_user_id', table_name='medical_event_drafts')
    op.drop_index('ix_medical_event_drafts_created_at', table_name='medical_event_drafts')
    op.drop_index('ix_medical_event_drafts_confirmed_event_id', table_name='medical_event_drafts')
    op.drop_table('medical_event_drafts')
    op.drop_index('ix_document_extraction_results_user_id', table_name='document_extraction_results')
    op.drop_index('ix_document_extraction_results_status', table_name='document_extraction_results')
    op.drop_index('ix_document_extraction_results_processing_job_id', table_name='document_extraction_results')
    op.drop_index('ix_document_extraction_results_family_id', table_name='document_extraction_results')
    op.drop_index('ix_document_extraction_results_document_id', table_name='document_extraction_results')
    op.drop_index('ix_document_extraction_results_created_at', table_name='document_extraction_results')
    op.drop_index('ix_document_extraction_results_confidence_level', table_name='document_extraction_results')
    op.drop_table('document_extraction_results')
    op.drop_index('uq_document_versions_document_id_version_no', table_name='document_versions')
    op.drop_index('ix_document_versions_document_id', table_name='document_versions')
    op.drop_index('ix_document_versions_created_by_user_id', table_name='document_versions')
    op.drop_index('ix_document_versions_created_at', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_document_processing_jobs_user_id', table_name='document_processing_jobs')
    op.drop_index('ix_document_processing_jobs_status', table_name='document_processing_jobs')
    op.drop_index('ix_document_processing_jobs_job_type', table_name='document_processing_jobs')
    op.drop_index('ix_document_processing_jobs_family_id', table_name='document_processing_jobs')
    op.drop_index('ix_document_processing_jobs_document_id', table_name='document_processing_jobs')
    op.drop_index('ix_document_processing_jobs_created_at', table_name='document_processing_jobs')
    op.drop_table('document_processing_jobs')
    op.drop_index('ix_alert_events_event_type', table_name='alert_events')
    op.drop_index('ix_alert_events_created_at', table_name='alert_events')
    op.drop_index('ix_alert_events_alert_id', table_name='alert_events')
    op.drop_index('ix_alert_events_actor_user_id', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('ix_medical_events_user_id', table_name='medical_events')
    op.drop_index('ix_medical_events_status', table_name='medical_events')
    op.drop_index('ix_medical_events_related_document_id', table_name='medical_events')
    op.drop_index('ix_medical_events_follow_up_needed', table_name='medical_events')
    op.drop_index('ix_medical_events_follow_up_at', table_name='medical_events')
    op.drop_index('ix_medical_events_family_id', table_name='medical_events')
    op.drop_index('ix_medical_events_event_type', table_name='medical_events')
    op.drop_index('ix_medical_events_event_date', table_name='medical_events')
    op.drop_index('ix_medical_events_created_by_user_id', table_name='medical_events')
    op.drop_index('ix_medical_events_created_at', table_name='medical_events')
    op.drop_table('medical_events')
    op.drop_index('ix_medical_documents_visibility', table_name='medical_documents')
    op.drop_index('ix_medical_documents_user_id', table_name='medical_documents')
    op.drop_index('ix_medical_documents_uploaded_by_user_id', table_name='medical_documents')
    op.drop_index('ix_medical_documents_family_id', table_name='medical_documents')
    op.drop_index('ix_medical_documents_document_type', table_name='medical_documents')
    op.drop_index('ix_medical_documents_document_date', table_name='medical_documents')
    op.drop_index('ix_medical_documents_created_at', table_name='medical_documents')
    op.drop_index('ix_medical_documents_ai_extract_status', table_name='medical_documents')
    op.drop_table('medical_documents')
    op.drop_index('ix_daily_reports_user_id', table_name='daily_reports')
    op.drop_index('ix_daily_reports_status_level', table_name='daily_reports')
    op.drop_index('ix_daily_reports_report_date', table_name='daily_reports')
    op.drop_index('ix_daily_reports_generation_status', table_name='daily_reports')
    op.drop_index('ix_daily_reports_family_id', table_name='daily_reports')
    op.drop_index('ix_daily_reports_created_at', table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index('ix_alerts_user_id', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_related_entity_type_related_entity_id', table_name='alerts')
    op.drop_index('ix_alerts_level', table_name='alerts')
    op.drop_index('ix_alerts_family_id', table_name='alerts')
    op.drop_index('ix_alerts_due_at', table_name='alerts')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_index('ix_alerts_alert_type', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
