"""add_agent_audit_tables

Revision ID: ae420c0ea01f
Revises: 97c8ad8504bb
Create Date: 2026-07-03 12:55:13.347976

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'ae420c0ea01f'
down_revision: str | None = '97c8ad8504bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_safety_checks',
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('workflow_name', sa.Enum('chat_workflow', 'free_text_record_workflow', 'document_extract_workflow', 'daily_report_workflow', 'doctor_visit_summary_workflow', 'health_knowledge_qa_workflow', name='agentworkflowname', native_enum=False, length=64), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('safety_level', sa.Enum('safe', 'caution', 'high_risk', 'blocked', name='agentsafetylevel', native_enum=False, length=32), nullable=False),
    sa.Column('safety_flags', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('was_rewritten', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=255), nullable=True),
    sa.Column('input_risk_summary', sa.Text(), nullable=True),
    sa.Column('original_answer_summary', sa.Text(), nullable=True),
    sa.Column('revised_answer_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_safety_checks_created_at', 'agent_safety_checks', ['created_at'], unique=False)
    op.create_index('ix_agent_safety_checks_intent', 'agent_safety_checks', ['intent'], unique=False)
    op.create_index('ix_agent_safety_checks_passed', 'agent_safety_checks', ['passed'], unique=False)
    op.create_index('ix_agent_safety_checks_request_id', 'agent_safety_checks', ['request_id'], unique=False)
    op.create_index('ix_agent_safety_checks_safety_level', 'agent_safety_checks', ['safety_level'], unique=False)
    op.create_index('ix_agent_safety_checks_was_rewritten', 'agent_safety_checks', ['was_rewritten'], unique=False)
    op.create_index('ix_agent_safety_checks_workflow_name', 'agent_safety_checks', ['workflow_name'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('workflow_name', sa.Enum('chat_workflow', 'free_text_record_workflow', 'document_extract_workflow', 'daily_report_workflow', 'doctor_visit_summary_workflow', 'health_knowledge_qa_workflow', name='agentworkflowname', native_enum=False, length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('access_mode', sa.Enum('read', 'write', 'draft', 'control', name='agenttoolaccessmode', native_enum=False, length=32), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='agenttoolrisklevel', native_enum=False, length=32), nullable=False),
    sa.Column('current_user_id', sa.Uuid(), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('permission_checked', sa.Boolean(), nullable=False),
    sa.Column('permission_result', sa.JSON(), nullable=True),
    sa.Column('input_summary', sa.JSON(), nullable=True),
    sa.Column('output_summary', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', 'skipped', 'blocked_by_permission', 'blocked_by_registry', 'blocked_by_guard', 'timeout', name='agenttoolcallstatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['current_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_tool_calls_access_mode', 'agent_tool_calls', ['access_mode'], unique=False)
    op.create_index('ix_agent_tool_calls_created_at', 'agent_tool_calls', ['created_at'], unique=False)
    op.create_index('ix_agent_tool_calls_current_user_id', 'agent_tool_calls', ['current_user_id'], unique=False)
    op.create_index('ix_agent_tool_calls_permission_checked', 'agent_tool_calls', ['permission_checked'], unique=False)
    op.create_index('ix_agent_tool_calls_request_id', 'agent_tool_calls', ['request_id'], unique=False)
    op.create_index('ix_agent_tool_calls_risk_level', 'agent_tool_calls', ['risk_level'], unique=False)
    op.create_index('ix_agent_tool_calls_status', 'agent_tool_calls', ['status'], unique=False)
    op.create_index('ix_agent_tool_calls_target_user_id', 'agent_tool_calls', ['target_user_id'], unique=False)
    op.create_index('ix_agent_tool_calls_tool_name', 'agent_tool_calls', ['tool_name'], unique=False)
    op.create_index('ix_agent_tool_calls_workflow_name', 'agent_tool_calls', ['workflow_name'], unique=False)
    op.create_table('agent_memories',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('memory_type', sa.Enum('user_preference', 'attention_focus', 'conversation_summary', 'health_summary_index', 'workflow_preference', name='agentmemorytype', native_enum=False, length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('user_input', 'workflow', 'system', 'manual', name='agentmemorysource', native_enum=False, length=32), nullable=False),
    sa.Column('source_entity_type', sa.String(length=100), nullable=True),
    sa.Column('source_entity_id', sa.Uuid(), nullable=True),
    sa.Column('confidence_level', sa.Enum('high', 'medium', 'low', 'unknown', name='confidencelevel', native_enum=False, length=32), nullable=False),
    sa.Column('visibility', sa.Enum('private', 'family_context', name='agentmemoryvisibility', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', 'deleted', 'expired', name='agentmemorystatus', native_enum=False, length=32), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_memories_confidence_level', 'agent_memories', ['confidence_level'], unique=False)
    op.create_index('ix_agent_memories_created_at', 'agent_memories', ['created_at'], unique=False)
    op.create_index('ix_agent_memories_expires_at', 'agent_memories', ['expires_at'], unique=False)
    op.create_index('ix_agent_memories_family_id', 'agent_memories', ['family_id'], unique=False)
    op.create_index('ix_agent_memories_last_used_at', 'agent_memories', ['last_used_at'], unique=False)
    op.create_index('ix_agent_memories_memory_type', 'agent_memories', ['memory_type'], unique=False)
    op.create_index('ix_agent_memories_source', 'agent_memories', ['source'], unique=False)
    op.create_index('ix_agent_memories_status', 'agent_memories', ['status'], unique=False)
    op.create_index('ix_agent_memories_target_user_id', 'agent_memories', ['target_user_id'], unique=False)
    op.create_index('ix_agent_memories_user_id', 'agent_memories', ['user_id'], unique=False)
    op.create_index('ix_agent_memories_visibility', 'agent_memories', ['visibility'], unique=False)
    op.create_table('agent_traces',
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('workflow_name', sa.Enum('chat_workflow', 'free_text_record_workflow', 'document_extract_workflow', 'daily_report_workflow', 'doctor_visit_summary_workflow', 'health_knowledge_qa_workflow', name='agentworkflowname', native_enum=False, length=64), nullable=False),
    sa.Column('trigger_type', sa.Enum('user_chat', 'free_text_record', 'document_upload', 'manual_report_generate', 'scheduled_report_generate', 'doctor_visit_summary', 'system_job', name='agenttriggertype', native_enum=False, length=64), nullable=False),
    sa.Column('current_user_id', sa.Uuid(), nullable=False),
    sa.Column('current_family_id', sa.Uuid(), nullable=True),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('source_page', sa.String(length=100), nullable=True),
    sa.Column('raw_input_summary', sa.Text(), nullable=True),
    sa.Column('final_output_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'partial_success', 'failed', 'blocked', 'permission_denied', 'cancelled', name='agenttracestatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['current_family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_traces_created_at', 'agent_traces', ['created_at'], unique=False)
    op.create_index('ix_agent_traces_current_family_id', 'agent_traces', ['current_family_id'], unique=False)
    op.create_index('ix_agent_traces_current_user_id', 'agent_traces', ['current_user_id'], unique=False)
    op.create_index('ix_agent_traces_request_id', 'agent_traces', ['request_id'], unique=True)
    op.create_index('ix_agent_traces_session_id', 'agent_traces', ['session_id'], unique=False)
    op.create_index('ix_agent_traces_started_at', 'agent_traces', ['started_at'], unique=False)
    op.create_index('ix_agent_traces_status', 'agent_traces', ['status'], unique=False)
    op.create_index('ix_agent_traces_target_user_id', 'agent_traces', ['target_user_id'], unique=False)
    op.create_index('ix_agent_traces_trigger_type', 'agent_traces', ['trigger_type'], unique=False)
    op.create_index('ix_agent_traces_workflow_name', 'agent_traces', ['workflow_name'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'view', 'export', 'share', 'login', 'logout', 'permission_change', 'agent_run', 'tool_call', 'safety_block', name='auditaction', native_enum=False, length=32), nullable=False),
    sa.Column('resource_type', sa.Enum('user', 'family', 'family_member', 'permission', 'health_profile', 'health_metric', 'blood_pressure_record', 'symptom_record', 'medical_event', 'medical_document', 'daily_report', 'alert', 'agent_trace', 'export_file', 'system', name='auditresourcetype', native_enum=False, length=64), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_family_id', 'audit_logs', ['family_id'], unique=False)
    op.create_index('ix_audit_logs_resource_id', 'audit_logs', ['resource_id'], unique=False)
    op.create_index('ix_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_index('ix_audit_logs_target_user_id', 'audit_logs', ['target_user_id'], unique=False)
    op.create_table('data_access_logs',
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('data_category', sa.Enum('profile', 'metrics', 'reports', 'symptoms', 'medical_events', 'documents', 'alerts', 'memory_summary', 'audit', name='dataaccesscategory', native_enum=False, length=64), nullable=False),
    sa.Column('action', sa.Enum('view', 'create', 'update', 'delete', 'generate', 'export', name='dataaccessaction', native_enum=False, length=32), nullable=False),
    sa.Column('access_reason', sa.String(length=255), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('permission_result', sa.JSON(), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_access_logs_action', 'data_access_logs', ['action'], unique=False)
    op.create_index('ix_data_access_logs_actor_user_id', 'data_access_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_data_access_logs_allowed', 'data_access_logs', ['allowed'], unique=False)
    op.create_index('ix_data_access_logs_created_at', 'data_access_logs', ['created_at'], unique=False)
    op.create_index('ix_data_access_logs_data_category', 'data_access_logs', ['data_category'], unique=False)
    op.create_index('ix_data_access_logs_family_id', 'data_access_logs', ['family_id'], unique=False)
    op.create_index('ix_data_access_logs_request_id', 'data_access_logs', ['request_id'], unique=False)
    op.create_index('ix_data_access_logs_resource_id', 'data_access_logs', ['resource_id'], unique=False)
    op.create_index('ix_data_access_logs_resource_type', 'data_access_logs', ['resource_type'], unique=False)
    op.create_index('ix_data_access_logs_target_user_id', 'data_access_logs', ['target_user_id'], unique=False)
    op.create_table('privacy_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('permission_updated', 'document_uploaded', 'document_deleted', 'data_exported', 'share_link_created', 'share_link_revoked', 'agent_accessed_data', 'user_deleted_data', 'account_deleted', name='privacyeventtype', native_enum=False, length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_privacy_events_actor_user_id', 'privacy_events', ['actor_user_id'], unique=False)
    op.create_index('ix_privacy_events_created_at', 'privacy_events', ['created_at'], unique=False)
    op.create_index('ix_privacy_events_event_type', 'privacy_events', ['event_type'], unique=False)
    op.create_index('ix_privacy_events_family_id', 'privacy_events', ['family_id'], unique=False)
    op.create_index('ix_privacy_events_user_id', 'privacy_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_privacy_events_user_id', table_name='privacy_events')
    op.drop_index('ix_privacy_events_family_id', table_name='privacy_events')
    op.drop_index('ix_privacy_events_event_type', table_name='privacy_events')
    op.drop_index('ix_privacy_events_created_at', table_name='privacy_events')
    op.drop_index('ix_privacy_events_actor_user_id', table_name='privacy_events')
    op.drop_table('privacy_events')
    op.drop_index('ix_data_access_logs_target_user_id', table_name='data_access_logs')
    op.drop_index('ix_data_access_logs_resource_type', table_name='data_access_logs')
    op.drop_index('ix_data_access_logs_resource_id', table_name='data_access_logs')
    op.drop_index('ix_data_access_logs_request_id', table_name='data_access_logs')
    op.drop_index('ix_data_access_logs_family_id', table_name='data_access_logs')
    op.drop_index('ix_data_access_logs_data_category', table_name='data_access_logs')
    op.drop_index('ix_data_access_logs_created_at', table_name='data_access_logs')
    op.drop_index('ix_data_access_logs_allowed', table_name='data_access_logs')
    op.drop_index('ix_data_access_logs_actor_user_id', table_name='data_access_logs')
    op.drop_index('ix_data_access_logs_action', table_name='data_access_logs')
    op.drop_table('data_access_logs')
    op.drop_index('ix_audit_logs_target_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_family_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_agent_traces_workflow_name', table_name='agent_traces')
    op.drop_index('ix_agent_traces_trigger_type', table_name='agent_traces')
    op.drop_index('ix_agent_traces_target_user_id', table_name='agent_traces')
    op.drop_index('ix_agent_traces_status', table_name='agent_traces')
    op.drop_index('ix_agent_traces_started_at', table_name='agent_traces')
    op.drop_index('ix_agent_traces_session_id', table_name='agent_traces')
    op.drop_index('ix_agent_traces_request_id', table_name='agent_traces')
    op.drop_index('ix_agent_traces_current_user_id', table_name='agent_traces')
    op.drop_index('ix_agent_traces_current_family_id', table_name='agent_traces')
    op.drop_index('ix_agent_traces_created_at', table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index('ix_agent_memories_visibility', table_name='agent_memories')
    op.drop_index('ix_agent_memories_user_id', table_name='agent_memories')
    op.drop_index('ix_agent_memories_target_user_id', table_name='agent_memories')
    op.drop_index('ix_agent_memories_status', table_name='agent_memories')
    op.drop_index('ix_agent_memories_source', table_name='agent_memories')
    op.drop_index('ix_agent_memories_memory_type', table_name='agent_memories')
    op.drop_index('ix_agent_memories_last_used_at', table_name='agent_memories')
    op.drop_index('ix_agent_memories_family_id', table_name='agent_memories')
    op.drop_index('ix_agent_memories_expires_at', table_name='agent_memories')
    op.drop_index('ix_agent_memories_created_at', table_name='agent_memories')
    op.drop_index('ix_agent_memories_confidence_level', table_name='agent_memories')
    op.drop_table('agent_memories')
    op.drop_index('ix_agent_tool_calls_workflow_name', table_name='agent_tool_calls')
    op.drop_index('ix_agent_tool_calls_tool_name', table_name='agent_tool_calls')
    op.drop_index('ix_agent_tool_calls_target_user_id', table_name='agent_tool_calls')
    op.drop_index('ix_agent_tool_calls_status', table_name='agent_tool_calls')
    op.drop_index('ix_agent_tool_calls_risk_level', table_name='agent_tool_calls')
    op.drop_index('ix_agent_tool_calls_request_id', table_name='agent_tool_calls')
    op.drop_index('ix_agent_tool_calls_permission_checked', table_name='agent_tool_calls')
    op.drop_index('ix_agent_tool_calls_current_user_id', table_name='agent_tool_calls')
    op.drop_index('ix_agent_tool_calls_created_at', table_name='agent_tool_calls')
    op.drop_index('ix_agent_tool_calls_access_mode', table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index('ix_agent_safety_checks_workflow_name', table_name='agent_safety_checks')
    op.drop_index('ix_agent_safety_checks_was_rewritten', table_name='agent_safety_checks')
    op.drop_index('ix_agent_safety_checks_safety_level', table_name='agent_safety_checks')
    op.drop_index('ix_agent_safety_checks_request_id', table_name='agent_safety_checks')
    op.drop_index('ix_agent_safety_checks_passed', table_name='agent_safety_checks')
    op.drop_index('ix_agent_safety_checks_intent', table_name='agent_safety_checks')
    op.drop_index('ix_agent_safety_checks_created_at', table_name='agent_safety_checks')
    op.drop_table('agent_safety_checks')
    # ### end Alembic commands ###
