# 模块领域：数据库迁移层
# 领域说明：负责用版本化脚本维护数据库结构变更。
# 文件职责：业务代码文件。承载本模块的一部分领域能力或工程能力。
# 维护原则：本文件只补充业务/工程注释，不在注释中改变任何运行逻辑。

"""add_identity_tables

Revision ID: c4d4c2b2ef2e
Revises: 202607030114
Create Date: 2026-07-03 01:37:38.068638

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'c4d4c2b2ef2e'
down_revision: str | None = '202607030114'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# 函数职责：数据库升级函数，创建或调整当前迁移版本需要的表、字段、索引和约束。
# 业务边界：迁移必须可重复追踪，不能依赖运行时业务状态。
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 流程说明：
    # 1. 按迁移版本声明数据库结构变化。
    # 2. 由 Alembic 在部署或本地开发时统一执行。
    # 3. 迁移脚本只处理结构，不处理业务数据解释。
    op.create_table('users',
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'unknown', name='gender', native_enum=False, length=32), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', 'deleted', name='userstatus', native_enum=False, length=32), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('login_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_sessions_expires_at', 'login_sessions', ['expires_at'], unique=False)
    op.create_index('ix_login_sessions_session_token_hash', 'login_sessions', ['session_token_hash'], unique=True)
    op.create_index('ix_login_sessions_user_id', 'login_sessions', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_auth_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('phone', 'email', 'wechat', 'google', 'apple', name='authprovider', native_enum=False, length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('union_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_auth_accounts_provider_provider_user_id')
    )
    op.create_index('ix_user_auth_accounts_provider_user_id', 'user_auth_accounts', ['provider_user_id'], unique=False)
    op.create_index('ix_user_auth_accounts_user_id', 'user_auth_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


# 函数职责：数据库回滚函数，撤销当前迁移版本引入的数据库结构变化。
# 业务边界：回滚顺序通常要与升级顺序相反，避免外键依赖失败。
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 流程说明：
    # 1. 按迁移版本声明数据库结构变化。
    # 2. 由 Alembic 在部署或本地开发时统一执行。
    # 3. 迁移脚本只处理结构，不处理业务数据解释。
    op.drop_index('ix_user_auth_accounts_user_id', table_name='user_auth_accounts')
    op.drop_index('ix_user_auth_accounts_provider_user_id', table_name='user_auth_accounts')
    op.drop_table('user_auth_accounts')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_login_sessions_user_id', table_name='login_sessions')
    op.drop_index('ix_login_sessions_session_token_hash', table_name='login_sessions')
    op.drop_index('ix_login_sessions_expires_at', table_name='login_sessions')
    op.drop_table('login_sessions')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
