# 模块领域：数据库迁移层
# 领域说明：负责用版本化脚本维护数据库结构变更。
# 文件职责：业务代码文件。承载本模块的一部分领域能力或工程能力。
# 维护原则：本文件只补充业务/工程注释，不在注释中改变任何运行逻辑。

"""add_health_core_tables

Revision ID: d6cf10a352c9
Revises: 278ab15ff9ab
Create Date: 2026-07-03 12:38:45.517435

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'd6cf10a352c9'
down_revision: str | None = '278ab15ff9ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# 函数职责：数据库升级函数，创建或调整当前迁移版本需要的表、字段、索引和约束。
# 业务边界：迁移必须可重复追踪，不能依赖运行时业务状态。
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 流程说明：
    # 1. 按迁移版本声明数据库结构变化。
    # 2. 由 Alembic 在部署或本地开发时统一执行。
    # 3. 迁移脚本只处理结构，不处理业务数据解释。
    op.create_table('blood_pressure_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('measurement_context', sa.Enum('morning', 'evening', 'before_medication', 'after_medication', 'after_exercise', 'unknown', name='bloodpressuremeasurementcontext', native_enum=False, length=32), nullable=False),
    sa.Column('arm', sa.Enum('left', 'right', 'unknown', name='bloodpressurearm', native_enum=False, length=32), nullable=False),
    sa.Column('posture', sa.Enum('sitting', 'standing', 'lying', 'unknown', name='bloodpressureposture', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.Enum('manual', 'ai_extracted', 'imported', 'device', 'system', 'unknown', name='metricsource', native_enum=False, length=32), nullable=False),
    sa.Column('confidence_level', sa.Enum('high', 'medium', 'low', 'unknown', name='confidencelevel', native_enum=False, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blood_pressure_records_diastolic', 'blood_pressure_records', ['diastolic'], unique=False)
    op.create_index('ix_blood_pressure_records_measured_at', 'blood_pressure_records', ['measured_at'], unique=False)
    op.create_index('ix_blood_pressure_records_systolic', 'blood_pressure_records', ['systolic'], unique=False)
    op.create_index('ix_blood_pressure_records_user_id', 'blood_pressure_records', ['user_id'], unique=False)
    op.create_index('ix_blood_pressure_records_user_id_measured_at', 'blood_pressure_records', ['user_id', 'measured_at'], unique=False)
    op.create_table('health_metrics',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('metric_type', sa.Enum('sleep_duration', 'steps', 'weight', 'bmi', 'body_fat', 'heart_rate', 'blood_oxygen', 'temperature', 'blood_glucose', 'exercise_duration', name='metrictype', native_enum=False, length=64), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('value_text', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('manual', 'ai_extracted', 'imported', 'device', 'system', 'unknown', name='metricsource', native_enum=False, length=32), nullable=False),
    sa.Column('source_detail', sa.String(length=255), nullable=True),
    sa.Column('confidence_level', sa.Enum('high', 'medium', 'low', 'unknown', name='confidencelevel', native_enum=False, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_metrics_measured_at', 'health_metrics', ['measured_at'], unique=False)
    op.create_index('ix_health_metrics_metric_type', 'health_metrics', ['metric_type'], unique=False)
    op.create_index('ix_health_metrics_source', 'health_metrics', ['source'], unique=False)
    op.create_index('ix_health_metrics_user_id', 'health_metrics', ['user_id'], unique=False)
    op.create_index('ix_health_metrics_user_id_metric_type_measured_at', 'health_metrics', ['user_id', 'metric_type', 'measured_at'], unique=False)
    op.create_table('health_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'unknown', name='gender', native_enum=False, length=32), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('blood_type', sa.Enum('A', 'B', 'AB', 'O', 'unknown', name='bloodtype', native_enum=False, length=16), nullable=True),
    sa.Column('health_goal', sa.String(length=500), nullable=True),
    sa.Column('chronic_conditions_summary', sa.String(length=1000), nullable=True),
    sa.Column('allergy_summary', sa.String(length=1000), nullable=True),
    sa.Column('medication_summary', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_health_profiles_user_id', 'health_profiles', ['user_id'], unique=False)
    op.create_table('health_data_import_jobs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('import_type', sa.Enum('manual_batch', 'csv', 'excel', 'device', 'system', name='healthdataimporttype', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.Enum('manual', 'ai_extracted', 'imported', 'device', 'system', 'unknown', name='metricsource', native_enum=False, length=32), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'success', 'failed', 'partial_success', 'cancelled', name='healthdataimportstatus', native_enum=False, length=32), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_data_import_jobs_created_at', 'health_data_import_jobs', ['created_at'], unique=False)
    op.create_index('ix_health_data_import_jobs_family_id', 'health_data_import_jobs', ['family_id'], unique=False)
    op.create_index('ix_health_data_import_jobs_source', 'health_data_import_jobs', ['source'], unique=False)
    op.create_index('ix_health_data_import_jobs_status', 'health_data_import_jobs', ['status'], unique=False)
    op.create_index('ix_health_data_import_jobs_user_id', 'health_data_import_jobs', ['user_id'], unique=False)
    op.create_table('health_record_drafts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('target_display_name', sa.String(length=100), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('draft_type', sa.Enum('symptom', 'metric_candidate', 'mixed_health_record', name='healthrecorddrafttype', native_enum=False, length=64), nullable=False),
    sa.Column('extracted_json', sa.JSON(), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('safety_flags', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.Enum('high', 'medium', 'low', 'unknown', name='confidencelevel', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'expired', name='healthrecorddraftstatus', native_enum=False, length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_record_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_record_drafts_created_at', 'health_record_drafts', ['created_at'], unique=False)
    op.create_index('ix_health_record_drafts_created_by_user_id', 'health_record_drafts', ['created_by_user_id'], unique=False)
    op.create_index('ix_health_record_drafts_expires_at', 'health_record_drafts', ['expires_at'], unique=False)
    op.create_index('ix_health_record_drafts_family_id', 'health_record_drafts', ['family_id'], unique=False)
    op.create_index('ix_health_record_drafts_status', 'health_record_drafts', ['status'], unique=False)
    op.create_index('ix_health_record_drafts_user_id', 'health_record_drafts', ['user_id'], unique=False)
    op.create_table('symptom_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('symptom_name', sa.String(length=100), nullable=True),
    sa.Column('body_part', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_text', sa.String(length=100), nullable=True),
    sa.Column('occurrence_time_text', sa.String(length=100), nullable=True),
    sa.Column('possible_trigger', sa.String(length=255), nullable=True),
    sa.Column('related_metric_types', sa.JSON(), nullable=True),
    sa.Column('action_taken', sa.String(length=500), nullable=True),
    sa.Column('follow_up_needed', sa.Boolean(), nullable=False),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'resolved', 'archived', name='symptomrecordstatus', native_enum=False, length=32), nullable=False),
    sa.Column('confidence_level', sa.Enum('high', 'medium', 'low', 'unknown', name='confidencelevel', native_enum=False, length=32), nullable=False),
    sa.Column('ai_summary', sa.String(length=1000), nullable=True),
    sa.Column('timeline_visible', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'ai_extracted', 'imported', 'system', name='healthrecordsource', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_symptom_records_created_at', 'symptom_records', ['created_at'], unique=False)
    op.create_index('ix_symptom_records_created_by_user_id', 'symptom_records', ['created_by_user_id'], unique=False)
    op.create_index('ix_symptom_records_family_id', 'symptom_records', ['family_id'], unique=False)
    op.create_index('ix_symptom_records_follow_up_needed', 'symptom_records', ['follow_up_needed'], unique=False)
    op.create_index('ix_symptom_records_started_at', 'symptom_records', ['started_at'], unique=False)
    op.create_index('ix_symptom_records_status', 'symptom_records', ['status'], unique=False)
    op.create_index('ix_symptom_records_symptom_name', 'symptom_records', ['symptom_name'], unique=False)
    op.create_index('ix_symptom_records_user_id', 'symptom_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


# 函数职责：数据库回滚函数，撤销当前迁移版本引入的数据库结构变化。
# 业务边界：回滚顺序通常要与升级顺序相反，避免外键依赖失败。
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 流程说明：
    # 1. 按迁移版本声明数据库结构变化。
    # 2. 由 Alembic 在部署或本地开发时统一执行。
    # 3. 迁移脚本只处理结构，不处理业务数据解释。
    op.drop_index('ix_symptom_records_user_id', table_name='symptom_records')
    op.drop_index('ix_symptom_records_symptom_name', table_name='symptom_records')
    op.drop_index('ix_symptom_records_status', table_name='symptom_records')
    op.drop_index('ix_symptom_records_started_at', table_name='symptom_records')
    op.drop_index('ix_symptom_records_follow_up_needed', table_name='symptom_records')
    op.drop_index('ix_symptom_records_family_id', table_name='symptom_records')
    op.drop_index('ix_symptom_records_created_by_user_id', table_name='symptom_records')
    op.drop_index('ix_symptom_records_created_at', table_name='symptom_records')
    op.drop_table('symptom_records')
    op.drop_index('ix_health_record_drafts_user_id', table_name='health_record_drafts')
    op.drop_index('ix_health_record_drafts_status', table_name='health_record_drafts')
    op.drop_index('ix_health_record_drafts_family_id', table_name='health_record_drafts')
    op.drop_index('ix_health_record_drafts_expires_at', table_name='health_record_drafts')
    op.drop_index('ix_health_record_drafts_created_by_user_id', table_name='health_record_drafts')
    op.drop_index('ix_health_record_drafts_created_at', table_name='health_record_drafts')
    op.drop_table('health_record_drafts')
    op.drop_index('ix_health_data_import_jobs_user_id', table_name='health_data_import_jobs')
    op.drop_index('ix_health_data_import_jobs_status', table_name='health_data_import_jobs')
    op.drop_index('ix_health_data_import_jobs_source', table_name='health_data_import_jobs')
    op.drop_index('ix_health_data_import_jobs_family_id', table_name='health_data_import_jobs')
    op.drop_index('ix_health_data_import_jobs_created_at', table_name='health_data_import_jobs')
    op.drop_table('health_data_import_jobs')
    op.drop_index('ix_health_profiles_user_id', table_name='health_profiles')
    op.drop_table('health_profiles')
    op.drop_index('ix_health_metrics_user_id_metric_type_measured_at', table_name='health_metrics')
    op.drop_index('ix_health_metrics_user_id', table_name='health_metrics')
    op.drop_index('ix_health_metrics_source', table_name='health_metrics')
    op.drop_index('ix_health_metrics_metric_type', table_name='health_metrics')
    op.drop_index('ix_health_metrics_measured_at', table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_index('ix_blood_pressure_records_user_id_measured_at', table_name='blood_pressure_records')
    op.drop_index('ix_blood_pressure_records_user_id', table_name='blood_pressure_records')
    op.drop_index('ix_blood_pressure_records_systolic', table_name='blood_pressure_records')
    op.drop_index('ix_blood_pressure_records_measured_at', table_name='blood_pressure_records')
    op.drop_index('ix_blood_pressure_records_diastolic', table_name='blood_pressure_records')
    op.drop_table('blood_pressure_records')
    # ### end Alembic commands ###
